#ifndef MENSAJES_CONEXION_H_
#define MENSAJES_CONEXION_H_

#include <Raknet/MessageIdentifiers.h>

enum GameMessages { //New enums for more events
	ID_PLAYER_JOIN = ID_USER_PACKET_ENUM + 1,
	ID_PLAYER_MOVE = ID_USER_PACKET_ENUM + 2,
	ID_EXISTING_PLAYER = ID_USER_PACKET_ENUM + 3,
	ID_PLAYER_DISCONNECT = ID_USER_PACKET_ENUM + 4,
	ID_START_GAME = ID_USER_PACKET_ENUM + 5,
	ID_ENEMY_MOVE = ID_USER_PACKET_ENUM + 6
};

#endif /* MENSAJES_CONEXION_H_ */
